language: node_js
matrix:
  include:
    - node_js: "0.10"
      script: "npm test"
    - node_js: "0.12"
      script: "npm test"
    - node_js: "4"
      script: "npm run travis"
    - node_js: "6"
      script: "npm run travis"
    - node_js: "8"
      script: "npm run travis"
